# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: "Álgebra Lineal"
tagline: "Facultad de Ciencias, UNAM." 
description: "Sitio web del curso de Álgebra Lineal. Aquí encontrarás el programa del curso, material de apoyo, recursos complementarios y algunas animaciones interactivas que te ayudarán a desarrollar una mejor intuición sobre los conceptos fundamentales. También se incorporarán herramientas computacionales que te permitirán explorar las ideas de manera visual y acercarte a métodos de trabajo utilizados en la ciencia y la investigación."
author: "Karen Escutia Solis"

baseurl: '/algebra-lineal'   # nombre de tu repositorio
url: 'https://karenescutia.github.io'   # cambia por tu usuario de GitHub

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.12.0

color_scheme: dark
search_enabled: true
heading_anchors: true
permalink: pretty

aux_links:
  GitHub del curso:
    - 'https://github.com/karenescutia/algebra-lineal'

footer_content: "© 2026 Karen Escutia Solis. Material académico para uso educativo."

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path:''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path:''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
